# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 27a4cd35709c60ea35bad8ac51b129489d716d9eba9cee570f0458f31954fa1fe80bfd0387db7dc3a056de3dca834f1b59c96d227102e564187c88fd46016526

test:
  secret_key_base: 5e75601093c290f5cb3c19c6fc9ce43df31382ab20e58afe14d18dcc3b4256f50fdb8fbd4f9cf8ba55bbb32b31e29c6efedcdb30743b39a9875fe42f694e4b35

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
